name: phd
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - packaging>=23.2
    - PyPDF2==3.0.1
    - typing_extensions==4.12.2
    - tornado==6.4
    - PyMuPDF==1.23.8
    - openai>=1.14.0
    - instructor>=1.2.3
    - langchain-community>=0.0.29
    - langchain-ollama>=0.1.0
    - faiss-cpu==1.8.0
    - langchain-text-splitters>=0.3.4
    - langchain-core>=0.3.26
    - ollama>=0.1.0
    - rank_bm25>=0.2.2
    - fuzzywuzzy>=0.18.0
    - python-Levenshtein>=0.23.0
